#include "GDT.h"

// explaination is in GDT.h
#define GDT_ACCESS__NULL_DESCRIPTOR 0x00
#define GDT_ACCESS__KERNEL_CODE_SEGMENT 0x9E
#define GDT_ACCESS__KERNEL_DATA_SEGMENT 0x92
#define GDT_ACCESS__USER_CODE_SEGMENT 0xFE
#define GDT_ACCESS__USER_DATA_SEGMENT 0xF2
#define GDT_ACCESS__TSS_SEGMENT 0x89

#define OFFSET_NULL_DESCRIPTOR 0x00
#define OFFSET_KERNEL_CODE_SEGMENT 0x08
#define OFFSET_KERNEL_DATA_SEGMENT 0x10
#define OFFSET_USER_CODE_SEGMENT 0x18
#define OFFSET_USER_DATA_SEGMENT 0x20
#define OFFSET_TSS_SEGMENT 0x28

#define LIMIT_NULL_DESCRIPTOR 0x00000
#define LIMIT_KERNEL_CODE_SEGMENT 0xFFFFF
#define LIMIT_KERNEL_DATA_SEGMENT 0xFFFFF
#define LIMIT_USER_CODE_SEGMENT 0xFFFFF
#define LIMIT_USER_DATA_SEGMENT 0xFFFFF
#define LIMIT_TSS_SEGMENT sizeof(TSS)-1

#define FLAGS_NULL_DESCRIPTOR 0x0
#define FLAGS_KERNEL_CODE_SEGMENT 0xA
#define FLAGS_KERNEL_DATA_SEGMENT 0xC
#define FLAGS_USER_CODE_SEGMENT 0xA
#define FLAGS_USER_DATA_SEGMENT 0xC
#define FLAGS_TSS_SEGMENT 0x0
